# Generated by Django 5.0.1 on 2026-02-07 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emission_factors', '0001_initial'),
        ('facilities', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 - Direct Emissions'), ('scope2', 'Scope 2 - Indirect Emissions (Electricity)'), ('scope3', 'Scope 3 - Other Indirect Emissions')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(max_length=50)),
                ('emission_factor_used', models.DecimalField(decimal_places=6, help_text='Snapshot of the EF value used at time of entry', max_digits=12)),
                ('co2e_calculated', models.DecimalField(decimal_places=4, help_text='Total emissions in kg CO2e (quantity * EF)', max_digits=15)),
                ('activity_date', models.DateField()),
                ('reporting_period', models.CharField(help_text='YYYY-MM format for aggregation', max_length=7)),
                ('data_source', models.CharField(blank=True, help_text="e.g., 'utility_bill', 'manual_entry'", max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified')], default='draft', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_emissions', to=settings.AUTH_USER_MODEL)),
                ('emission_factor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='emission_factors.emissionfactor')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='facilities.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='organizations.organization')),
            ],
            options={
                'db_table': 'emission_records',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScopeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('emission_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scope_details', to='emissions.emissionrecord')),
            ],
            options={
                'verbose_name_plural': 'Scope Details',
                'db_table': 'scope_details',
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'reporting_period'], name='emission_re_organiz_362bde_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['facility', 'reporting_period'], name='emission_re_facilit_d0a128_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['scope', 'category'], name='emission_re_scope_4d3b41_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['activity_date'], name='emission_re_activit_afed01_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['status'], name='emission_re_status_6f7f38_idx'),
        ),
    ]
