# Generated by Django 5.0.1 on 2026-02-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='reporting_period',
            field=models.CharField(blank=True, help_text='YYYY-MM format for aggregation', max_length=7),
        ),
    ]
