# Generated by Django 5.0.1 on 2026-02-07 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Facility name', max_length=255)),
                ('facility_type', models.CharField(blank=True, choices=[('office', 'Office'), ('manufacturing', 'Manufacturing Plant'), ('warehouse', 'Warehouse'), ('retail', 'Retail Store'), ('data_center', 'Data Center'), ('other', 'Other')], help_text='Type of facility', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('grid_region', models.CharField(blank=True, help_text="Electricity grid region (e.g., 'US', 'India-Northern', 'EU-Germany')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'db_table': 'facilities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'name'], name='facilities_organiz_ad1733_idx'), models.Index(fields=['country'], name='facilities_country_1fe8b5_idx'), models.Index(fields=['grid_region'], name='facilities_grid_re_fea62c_idx')],
            },
        ),
    ]
