# Generated by Django 5.0.1 on 2026-02-07 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 - Direct Emissions'), ('scope2', 'Scope 2 - Indirect Emissions (Electricity)'), ('scope3', 'Scope 3 - Other Indirect Emissions')], max_length=10)),
                ('category', models.CharField(help_text="Emission category (e.g., 'Diesel', 'Electricity')", max_length=100)),
                ('subcategory', models.CharField(blank=True, help_text="Subcategory (e.g., 'Economy Class')", max_length=100)),
                ('emission_factor_co2e', models.DecimalField(decimal_places=6, help_text='kg CO2e per unit', max_digits=12)),
                ('unit', models.CharField(help_text="Unit (e.g., 'liter', 'kWh', 'km', 'kg')", max_length=50)),
                ('region', models.CharField(default='Global', help_text='Region for this factor', max_length=100)),
                ('source', models.CharField(blank=True, help_text="Data source (e.g., 'IPCC 2024')", max_length=255)),
                ('valid_year', models.IntegerField(default=2024, help_text='Year this factor is valid for')),
            ],
            options={
                'db_table': 'emission_factors',
                'ordering': ['scope', 'category', 'subcategory'],
                'indexes': [models.Index(fields=['scope', 'category', 'region'], name='emission_fa_scope_40ebf4_idx')],
                'unique_together': {('scope', 'category', 'subcategory', 'region', 'valid_year')},
            },
        ),
    ]
