# Generated by Django 5.0.1 on 2026-02-07 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionSummaryMonthly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reporting_period', models.CharField(max_length=7)),
                ('scope', models.CharField(blank=True, max_length=10)),
                ('total_co2e', models.DecimalField(decimal_places=4, max_digits=15)),
                ('record_count', models.IntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='facilities.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='organizations.organization')),
            ],
            options={
                'db_table': 'emission_summary_monthly',
                'indexes': [models.Index(fields=['organization', 'reporting_period'], name='emission_su_organiz_350f72_idx'), models.Index(fields=['organization', 'scope'], name='emission_su_organiz_a51181_idx')],
                'unique_together': {('organization', 'facility', 'reporting_period', 'scope')},
            },
        ),
    ]
