# Generated by Django 5.0.1 on 2026-02-07 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Organization name', max_length=255)),
                ('industry', models.CharField(blank=True, help_text='Industry sector', max_length=100)),
                ('country', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('baseline_year', models.IntegerField(default=2023, help_text='Baseline year for emissions tracking')),
                ('fiscal_year_start', models.CharField(default='01-01', help_text='Fiscal year start (MM-DD format)', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='organizatio_name_5cd1d4_idx'), models.Index(fields=['industry'], name='organizatio_industr_24ff5e_idx')],
            },
        ),
    ]
